[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { workspace = true }

[build-dependencies]
risc0-build = { workspace = true }
risc0-build-ethereum = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]
